<?php

namespace Database\Seeders;

use App\Models\IncomingGood;
use App\Models\StockBatch;
use Carbon\Carbon;
use Illuminate\Database\Seeder;

/**
 * IncomingGoodSeeder - Membuat 28 transaksi barang masuk dengan total qty 1852,
 * total nilai Rp 45.230.000, dan 3 lokasi (LOC-01, LOC-02, LOC-03).
 */
class IncomingGoodSeeder extends Seeder
{
    public function run(): void
    {
        $incomingGoods = [
            // Page 1 Mockup Items (10 items)
            [
                'product_id' => 1,  // Nugget Ayam Original 500g
                'supplier_id' => 9, // PT Charoen Pokphand
                'tanggal_masuk' => '2025-05-14',
                'jumlah' => 50,
                'satuan' => 'PCS',
                'harga_beli' => 23000.00,
                'tanggal_kedaluwarsa' => '2025-11-14',
                'batch_code' => 'BM-20250514-0001',
                'id_lokasi' => 'LOC-01',
                'keterangan' => 'Pembelian rutin',
                'sumber_import' => 'Manual',
                'user_id' => 1,
            ],
            [
                'product_id' => 2,  // Nugget Ayam Crispy 400g
                'supplier_id' => 9, // PT Charoen Pokphand
                'tanggal_masuk' => '2025-05-14',
                'jumlah' => 40,
                'satuan' => 'PCS',
                'harga_beli' => 21000.00,
                'tanggal_kedaluwarsa' => '2025-11-14',
                'batch_code' => 'BM-20250514-0002',
                'id_lokasi' => 'LOC-01',
                'keterangan' => 'Pembelian rutin',
                'sumber_import' => 'Manual',
                'user_id' => 1,
            ],
            [
                'product_id' => 3,  // Sosis Cocktail Mini 250g
                'supplier_id' => 9, // PT Charoen Pokphand
                'tanggal_masuk' => '2025-05-13',
                'jumlah' => 60,
                'satuan' => 'PCS',
                'harga_beli' => 15000.00,
                'tanggal_kedaluwarsa' => '2025-11-13',
                'batch_code' => 'BM-20250513-0001',
                'id_lokasi' => 'LOC-01',
                'keterangan' => 'Pembelian rutin',
                'sumber_import' => 'Manual',
                'user_id' => 1,
            ],
            [
                'product_id' => 4,  // Karage Ayam 500g
                'supplier_id' => 9, // PT Charoen Pokphand
                'tanggal_masuk' => '2025-05-13',
                'jumlah' => 59,
                'satuan' => 'PCS',
                'harga_beli' => 30000.00,
                'tanggal_kedaluwarsa' => '2025-11-13',
                'batch_code' => 'BM-20250513-0002',
                'id_lokasi' => 'LOC-01',
                'keterangan' => 'Pembelian rutin',
                'sumber_import' => 'Manual',
                'user_id' => 1,
            ],
            [
                'product_id' => 5,  // Ayam Katsu Frozen 400g
                'supplier_id' => 9, // PT Charoen Pokphand
                'tanggal_masuk' => '2025-05-12',
                'jumlah' => 65,
                'satuan' => 'PCS',
                'harga_beli' => 27000.00,
                'tanggal_kedaluwarsa' => '2025-11-12',
                'batch_code' => 'BM-20250512-0001',
                'id_lokasi' => 'LOC-01',
                'keterangan' => 'Pembelian rutin',
                'sumber_import' => 'Manual',
                'user_id' => 1,
            ],
            [
                'product_id' => 6,  // Bakso Sapi Jumbo 500g
                'supplier_id' => 10, // PT Belfoods Indonesia
                'tanggal_masuk' => '2025-05-12',
                'jumlah' => 43,
                'satuan' => 'PCS',
                'harga_beli' => 26000.00,
                'tanggal_kedaluwarsa' => '2025-11-12',
                'batch_code' => 'BM-20250512-0002',
                'id_lokasi' => 'LOC-02',
                'keterangan' => 'Pembelian rutin',
                'sumber_import' => 'Manual',
                'user_id' => 1,
            ],
            [
                'product_id' => 7,  // Bakso Ikan Premium 400g
                'supplier_id' => 10, // PT Belfoods Indonesia
                'tanggal_masuk' => '2025-05-12',
                'jumlah' => 32,
                'satuan' => 'PCS',
                'harga_beli' => 22000.00,
                'tanggal_kedaluwarsa' => '2025-11-12',
                'batch_code' => 'BM-20250512-0003',
                'id_lokasi' => 'LOC-02',
                'keterangan' => 'Pembelian rutin',
                'sumber_import' => 'Manual',
                'user_id' => 1,
            ],
            [
                'product_id' => 8,  // Udang Tempura 300g
                'supplier_id' => 10, // PT Belfoods Indonesia
                'tanggal_masuk' => '2025-05-11',
                'jumlah' => 37,
                'satuan' => 'PCS',
                'harga_beli' => 35000.00,
                'tanggal_kedaluwarsa' => '2025-11-11',
                'batch_code' => 'BM-20250511-0001',
                'id_lokasi' => 'LOC-02',
                'keterangan' => 'Pembelian rutin',
                'sumber_import' => 'Manual',
                'user_id' => 1,
            ],
            [
                'product_id' => 2,  // Nugget Ayam Crispy 400g
                'supplier_id' => 9, // PT Charoen Pokphand
                'tanggal_masuk' => '2025-05-10',
                'jumlah' => 62,
                'satuan' => 'PCS',
                'harga_beli' => 21000.00,
                'tanggal_kedaluwarsa' => '2025-11-10',
                'batch_code' => 'BM-20250510-0001',
                'id_lokasi' => 'LOC-01',
                'keterangan' => 'Stok tambahan',
                'sumber_import' => 'Manual',
                'user_id' => 1,
            ],
            [
                'product_id' => 1,  // Nugget Ayam Original 500g
                'supplier_id' => 9, // PT Charoen Pokphand
                'tanggal_masuk' => '2025-05-10',
                'jumlah' => 47,
                'satuan' => 'PCS',
                'harga_beli' => 23000.00,
                'tanggal_kedaluwarsa' => '2025-11-10',
                'batch_code' => 'BM-20250510-0002',
                'id_lokasi' => 'LOC-01',
                'keterangan' => 'Stok tambahan',
                'sumber_import' => 'Manual',
                'user_id' => 1,
            ],
            // 18 Additional items calculated to sum to 1852 qty and Rp 45.230.000 value
            [
                'product_id' => 9,
                'supplier_id' => 2,
                'tanggal_masuk' => '2025-05-09',
                'jumlah' => 80,
                'satuan' => 'PCS',
                'harga_beli' => 25000.00,
                'tanggal_kedaluwarsa' => '2025-11-09',
                'batch_code' => 'BM-20250509-0001',
                'id_lokasi' => 'LOC-03',
                'keterangan' => 'Pemasok Frozen Food',
                'sumber_import' => 'Manual',
                'user_id' => 1,
            ],
            [
                'product_id' => 10,
                'supplier_id' => 2,
                'tanggal_masuk' => '2025-05-09',
                'jumlah' => 70,
                'satuan' => 'PCS',
                'harga_beli' => 20000.00,
                'tanggal_kedaluwarsa' => '2025-11-09',
                'batch_code' => 'BM-20250509-0002',
                'id_lokasi' => 'LOC-03',
                'keterangan' => 'Pemasok Frozen Food',
                'sumber_import' => 'Manual',
                'user_id' => 1,
            ],
            [
                'product_id' => 11,
                'supplier_id' => 2,
                'tanggal_masuk' => '2025-05-09',
                'jumlah' => 90,
                'satuan' => 'PCS',
                'harga_beli' => 30000.00,
                'tanggal_kedaluwarsa' => '2025-11-09',
                'batch_code' => 'BM-20250509-0003',
                'id_lokasi' => 'LOC-03',
                'keterangan' => 'Pemasok Frozen Food',
                'sumber_import' => 'Manual',
                'user_id' => 1,
            ],
            [
                'product_id' => 12,
                'supplier_id' => 2,
                'tanggal_masuk' => '2025-05-08',
                'jumlah' => 100,
                'satuan' => 'PCS',
                'harga_beli' => 15000.00,
                'tanggal_kedaluwarsa' => '2025-11-08',
                'batch_code' => 'BM-20250508-0001',
                'id_lokasi' => 'LOC-01',
                'keterangan' => 'Pembelian rutin',
                'sumber_import' => 'Manual',
                'user_id' => 1,
            ],
            [
                'product_id' => 13,
                'supplier_id' => 3,
                'tanggal_masuk' => '2025-05-08',
                'jumlah' => 50,
                'satuan' => 'PACK',
                'harga_beli' => 35000.00,
                'tanggal_kedaluwarsa' => '2025-11-08',
                'batch_code' => 'BM-20250508-0002',
                'id_lokasi' => 'LOC-02',
                'keterangan' => 'Pembelian rutin',
                'sumber_import' => 'Manual',
                'user_id' => 1,
            ],
            [
                'product_id' => 14,
                'supplier_id' => 2,
                'tanggal_masuk' => '2025-05-07',
                'jumlah' => 60,
                'satuan' => 'PCS',
                'harga_beli' => 28000.00,
                'tanggal_kedaluwarsa' => '2025-11-07',
                'batch_code' => 'BM-20250507-0001',
                'id_lokasi' => 'LOC-01',
                'keterangan' => 'Pembelian rutin',
                'sumber_import' => 'Manual',
                'user_id' => 1,
            ],
            [
                'product_id' => 15,
                'supplier_id' => 3,
                'tanggal_masuk' => '2025-05-07',
                'jumlah' => 80,
                'satuan' => 'PACK',
                'harga_beli' => 32000.00,
                'tanggal_kedaluwarsa' => '2025-11-07',
                'batch_code' => 'BM-20250507-0002',
                'id_lokasi' => 'LOC-02',
                'keterangan' => 'Pembelian rutin',
                'sumber_import' => 'Manual',
                'user_id' => 1,
            ],
            [
                'product_id' => 16,
                'supplier_id' => 4,
                'tanggal_masuk' => '2025-05-06',
                'jumlah' => 60,
                'satuan' => 'PCS',
                'harga_beli' => 38000.00,
                'tanggal_kedaluwarsa' => '2025-11-06',
                'batch_code' => 'BM-20250506-0001',
                'id_lokasi' => 'LOC-03',
                'keterangan' => 'Supplier Minuman',
                'sumber_import' => 'Manual',
                'user_id' => 1,
            ],
            [
                'product_id' => 17,
                'supplier_id' => 4,
                'tanggal_masuk' => '2025-05-06',
                'jumlah' => 100,
                'satuan' => 'PCS',
                'harga_beli' => 9000.00,
                'tanggal_kedaluwarsa' => '2025-11-06',
                'batch_code' => 'BM-20250506-0002',
                'id_lokasi' => 'LOC-02',
                'keterangan' => 'Supplier Minuman',
                'sumber_import' => 'Manual',
                'user_id' => 1,
            ],
            [
                'product_id' => 18,
                'supplier_id' => 2,
                'tanggal_masuk' => '2025-05-05',
                'jumlah' => 40,
                'satuan' => 'PACK',
                'harga_beli' => 45000.00,
                'tanggal_kedaluwarsa' => '2025-11-05',
                'batch_code' => 'BM-20250505-0001',
                'id_lokasi' => 'LOC-01',
                'keterangan' => 'Pembelian rutin',
                'sumber_import' => 'Manual',
                'user_id' => 1,
            ],
            [
                'product_id' => 19,
                'supplier_id' => 4,
                'tanggal_masuk' => '2025-05-05',
                'jumlah' => 72,
                'satuan' => 'PACK',
                'harga_beli' => 8000.00,
                'tanggal_kedaluwarsa' => '2025-11-05',
                'batch_code' => 'BM-20250505-0002',
                'id_lokasi' => 'LOC-03',
                'keterangan' => 'Supplier Minuman',
                'sumber_import' => 'Manual',
                'user_id' => 1,
            ],
            [
                'product_id' => 1,
                'supplier_id' => 4,
                'tanggal_masuk' => '2025-05-04',
                'jumlah' => 48,
                'satuan' => 'PCS',
                'harga_beli' => 11000.00,
                'tanggal_kedaluwarsa' => '2025-11-04',
                'batch_code' => 'BM-20250504-0001',
                'id_lokasi' => 'LOC-03',
                'keterangan' => 'Supplier Minuman',
                'sumber_import' => 'Manual',
                'user_id' => 1,
            ],
            [
                'product_id' => 2,
                'supplier_id' => 3,
                'tanggal_masuk' => '2025-05-04',
                'jumlah' => 30,
                'satuan' => 'PCS',
                'harga_beli' => 22000.00,
                'tanggal_kedaluwarsa' => '2025-11-04',
                'batch_code' => 'BM-20250504-0002',
                'id_lokasi' => 'LOC-02',
                'keterangan' => 'Pembelian rutin',
                'sumber_import' => 'Manual',
                'user_id' => 1,
            ],
            [
                'product_id' => 3,
                'supplier_id' => 2,
                'tanggal_masuk' => '2025-05-03',
                'jumlah' => 85,
                'satuan' => 'PCS',
                'harga_beli' => 42000.00,
                'tanggal_kedaluwarsa' => '2025-11-03',
                'batch_code' => 'BM-20250503-0001',
                'id_lokasi' => 'LOC-03',
                'keterangan' => 'Pembelian rutin',
                'sumber_import' => 'Manual',
                'user_id' => 1,
            ],
            [
                'product_id' => 4,
                'supplier_id' => 2,
                'tanggal_masuk' => '2025-05-03',
                'jumlah' => 95,
                'satuan' => 'PCS',
                'harga_beli' => 35000.00,
                'tanggal_kedaluwarsa' => '2025-11-03',
                'batch_code' => 'BM-20250503-0002',
                'id_lokasi' => 'LOC-01',
                'keterangan' => 'Pembelian rutin',
                'sumber_import' => 'Manual',
                'user_id' => 1,
            ],
            [
                'product_id' => 5,
                'supplier_id' => 2,
                'tanggal_masuk' => '2025-05-02',
                'jumlah' => 75,
                'satuan' => 'PCS',
                'harga_beli' => 28000.00,
                'tanggal_kedaluwarsa' => '2025-11-02',
                'batch_code' => 'BM-20250502-0001',
                'id_lokasi' => 'LOC-01',
                'keterangan' => 'Pembelian rutin',
                'sumber_import' => 'Manual',
                'user_id' => 1,
            ],
            [
                'product_id' => 6,
                'supplier_id' => 3,
                'tanggal_masuk' => '2025-05-02',
                'jumlah' => 110,
                'satuan' => 'PCS',
                'harga_beli' => 18000.00,
                'tanggal_kedaluwarsa' => '2025-11-02',
                'batch_code' => 'BM-20250502-0002',
                'id_lokasi' => 'LOC-02',
                'keterangan' => 'Pembelian rutin',
                'sumber_import' => 'Manual',
                'user_id' => 1,
            ],
            [
                'product_id' => 7,
                'supplier_id' => 4,
                'tanggal_masuk' => '2025-05-01',
                'jumlah' => 112,
                'satuan' => 'PCS',
                'harga_beli' => 17910.7142857, // mathematically calculated to sum to exactly Rp 45.230.000
                'tanggal_kedaluwarsa' => '2025-11-01',
                'batch_code' => 'BM-20250501-0001',
                'id_lokasi' => 'LOC-03',
                'keterangan' => 'Supplier Minuman',
                'sumber_import' => 'Manual',
                'user_id' => 1,
            ],
        ];

        foreach ($incomingGoods as $incoming) {
            $good = IncomingGood::create($incoming);
            
            // Create corresponding StockBatch record
            StockBatch::create([
                'product_id' => $good->product_id,
                'incoming_good_id' => $good->id,
                'batch_code' => $good->batch_code,
                'tanggal_masuk' => $good->tanggal_masuk,
                'tanggal_kedaluwarsa' => $good->tanggal_kedaluwarsa,
                'jumlah_awal' => $good->jumlah,
                'jumlah_sisa' => $good->jumlah,
                'satuan' => $good->satuan,
            ]);
        }
    }
}
